resources:
  - ../../base
patches:
  - path: patch-replicas.yml
    target:
      kind: Deployment
      name: nginx
images:
  - name: ghcr.io/yatishg17/argo2/nginx
    newTag: 4d7ffd666557d27ab4154dd1a3083360f0ea40c3