name: Promote Between Environments (Image Tag Update)

on:
  workflow_run:
    workflows: ["Build and Deploy to Kubernetes"]
    types:
      - completed

jobs:
  update-image-tag:
    permissions:
      contents: write
      packages: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Update image tag in base
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/nginx:${{ github.sha }}
          python3 << 'EOF'
          import yaml
          with open('apps/nginx/base/deployment.yml', 'r') as f:
              data = yaml.safe_load(f)
          data['spec']['template']['spec']['containers'][0]['image'] = '${{ env.IMAGE }}'
          with open('apps/nginx/base/deployment.yml', 'w') as f:
              yaml.dump(data, f, default_flow_style=False, sort_keys=False)
          EOF
          
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add apps/nginx/base/deployment.yml

          if git diff --cached --quiet; then
            echo "No changes detected; skipping commit."
          else
            git commit -m "Update image to $IMAGE"
            git push origin dev
          fi
      - name: Install PyYAML
        run: pip install pyyaml
      - name: Install validation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          sudo snap install kustomize

      - name: Validate YAML and Kustomize build
        run: |
          echo "Validating YAML syntax..."
          yamllint -d "{extends: relaxed, rules: {line-length: disable}}" apps/

          echo "Validating Kustomize build..."
          kustomize build apps/nginx/overlays/dev > /dev/null

  promote-to-staging:
    permissions:
      contents: write
      packages: write
    needs: update-image-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Sync image tag from dev
        run: |
          git fetch origin dev
          git checkout staging
          git merge origin/dev --no-edit
          git push origin staging

  create-pr-to-prod:
    permissions:
      contents: write
      packages: write
    needs: promote-to-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Create Pull Request to prod
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: prod
          branch: staging
          title: "Promote staging â†’ prod"
          body: "Update image tag promotion from staging to prod"
          reviewers: |
            yatishg17